### PR TITLE
Yumi development

### PR DESCRIPTION
**Pull request by yumip**
responsive navbar
I can change the background colour later

### CODE REVIEW

**Comment by BabkinAV** [comment]
Looks cool! Maybe the only suggestion  is to add **cursor: pointer** property to **.humburger** class for better usability

**Comment by yumip** [comment]
Thanks, @BabkinAV  I just added a cursor :-)

**Comment by omegapaulo** [comment]
This looks very good Yumi

**Review by omegapaulo — APPROVED** [review]
Approved with an A+++++

**Pull request merged**
